import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import math

# --- 1. Synthetic Continual Learning Dataset ---
VOCAB_SIZE = 100
SEQ_LEN = 16
BATCH_SIZE = 64
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def generate_task_data(task_id, num_samples):
    X, Y = [], []
    for _ in range(num_samples):
        if task_id == 0:
            start = np.random.randint(0, 50) * 2
            seq = [(start + i * 2) % VOCAB_SIZE for i in range(SEQ_LEN + 1)]
        elif task_id == 1:
            start = np.random.randint(0, 50) * 2 + 1
            seq = [(start + i * 2) % VOCAB_SIZE for i in range(SEQ_LEN + 1)]
        else:
            start = np.random.randint(0, VOCAB_SIZE)
            seq = [(start + i * 5) % VOCAB_SIZE for i in range(SEQ_LEN + 1)]
        X.append(seq[:-1]); Y.append(seq[1:])
    return torch.tensor(X, dtype=torch.long, device=DEVICE), torch.tensor(Y, dtype=torch.long, device=DEVICE)

# --- 2. Hyper-Adapter Layer ---
# This layer has a base weight (frozen) and a dynamic LoRA weight 
# generated by a Hyper-Network based on the input context.
class HyperLoRALinear(nn.Module):
    def __init__(self, in_features, out_features, rank=8, context_dim=128):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.rank = rank
        
        self.base = nn.Linear(in_features, out_features)
        self.base.weight.requires_grad = False
        
        # Hyper-Network for LoRA A and B
        # A: (in, rank), B: (rank, out)
        self.hyper_a = nn.Linear(context_dim, in_features * rank)
        self.hyper_b = nn.Linear(context_dim, rank * out_features)
        
        # Initialize hyper-networks to output near-zero B for stability
        nn.init.zeros_(self.hyper_b.weight)
        nn.init.zeros_(self.hyper_b.bias)

    def forward(self, x, context):
        # x: (B, T, in), context: (B, context_dim)
        B, T, _ = x.size()
        
        # Generate LoRA weights
        lora_a = self.hyper_a(context).view(B, self.in_features, self.rank)
        lora_b = self.hyper_b(context).view(B, self.rank, self.out_features)
        
        # Base path
        base_out = self.base(x)
        
        # LoRA path: (B, T, in) @ (B, in, rank) @ (B, rank, out) -> (B, T, out)
        # Using batch matrix multiplication
        lora_out = torch.bmm(torch.bmm(x, lora_a), lora_b)
        
        return base_out + lora_out

# --- 3. Hyper-Rocket Transformer ---
class HyperRocketBlock(nn.Module):
    def __init__(self, d_model, n_heads, rank=8):
        super().__init__()
        self.ln1 = nn.LayerNorm(d_model)
        self.q_proj = HyperLoRALinear(d_model, d_model, rank)
        self.k_proj = nn.Linear(d_model, d_model)
        self.v_proj = HyperLoRALinear(d_model, d_model, rank)
        self.ln2 = nn.LayerNorm(d_model)
        self.mlp_lora = HyperLoRALinear(d_model, d_model, rank)
        self.n_heads = n_heads

    def forward(self, x, context):
        B, T, C = x.size()
        res = x
        x = self.ln1(x)
        
        q = self.q_proj(x, context).view(B, T, self.n_heads, C // self.n_heads).transpose(1, 2)
        k = self.k_proj(x).view(B, T, self.n_heads, C // self.n_heads).transpose(1, 2)
        v = self.v_proj(x, context).view(B, T, self.n_heads, C // self.n_heads).transpose(1, 2)
        
        attn = F.scaled_dot_product_attention(q, k, v, is_causal=True)
        attn = attn.transpose(1, 2).contiguous().view(B, T, C)
        x = res + attn
        
        res = x
        x = self.ln2(x)
        # Simple MLP approximation using the hyper-adapter
        x = res + self.mlp_lora(F.gelu(x), context)
        return x

class HyperRocket(nn.Module):
    def __init__(self, vocab_size, d_model=128, n_heads=4, n_layers=2):
        super().__init__()
        self.d_model = d_model
        self.emb = nn.Embedding(vocab_size, d_model)
        self.pos = nn.Parameter(torch.randn(SEQ_LEN, d_model))
        
        # Context extractor (moving average of embeddings)
        self.context_net = nn.Sequential(
            nn.Linear(d_model, d_model),
            nn.GELU(),
            nn.Linear(d_model, d_model)
        )
        
        self.blocks = nn.ModuleList([HyperRocketBlock(d_model, n_heads) for _ in range(n_layers)])
        self.ln_f = nn.LayerNorm(d_model)
        self.head = nn.Linear(d_model, vocab_size)
        
    def forward(self, x):
        B, T = x.size()
        x_emb = self.emb(x) + self.pos
        
        # Extract context from the sequence itself
        # In a real streaming scenario, this would be a rolling average state.
        context = self.context_net(x_emb.mean(dim=1)) # (B, d_model)
        
        for block in self.blocks:
            x_emb = block(x_emb, context)
            
        x_emb = self.ln_f(x_emb)
        logits = self.head(x_emb)
        return logits

# --- 4. Training and Evaluation ---
def train_hyper(model, x, y):
    optimizer = optim.Adam(model.parameters(), lr=1e-3)
    model.train()
    for ep in range(10):
        for i in range(0, len(x), BATCH_SIZE):
            bx, by = x[i:i+BATCH_SIZE], y[i:i+BATCH_SIZE]
            optimizer.zero_grad()
            logits = model(bx)
            loss = F.cross_entropy(logits.view(-1, VOCAB_SIZE), by.view(-1))
            loss.backward()
            optimizer.step()

def evaluate(model, x, y):
    model.eval()
    with torch.no_grad():
        logits = model(x)
        return F.cross_entropy(logits.view(-1, VOCAB_SIZE), y.view(-1)).item()

if __name__ == "__main__":
    print(f"\n{'='*50}\nRunning Hyper-Rocket (Dynamic Structure Patching)\n{'='*50}")
    model = HyperRocket(VOCAB_SIZE).to(DEVICE)
    
    tasks = [generate_task_data(i, 2000) for i in range(3)]
    test_tasks = [generate_task_data(i, 500) for i in range(3)]
    
    for t_id, (x, y) in enumerate(tasks):
        print(f"\n--- Training on Task {t_id} ---")
        train_hyper(model, x, y)
        
        for eval_id, (tx, ty) in enumerate(test_tasks):
            loss = evaluate(model, tx, ty)
            print(f"Eval Task {eval_id} Loss: {loss:.4f}")

